import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useAuth } from "../../auth/authStore";
import QuotationForm from "../components/QuotationForm";
import { changeQuotationStatus, deleteQuotation, getQuotations, reviseQuotation, adminVerifyProposal, clientDecideProposal } from "../quotationApi";
import "../quotation.css";

const errorFor = (error) => error.response?.data?.message || "Unable to complete the request.";

function QuotationList() {
    const { user } = useAuth();
    const isClientRole = user?.role === "client";
    const isAdmin = user?.role === "admin";
    const isManager = user?.role === "manager";

    const [records, setRecords] = useState([]);
    const [selected, setSelected] = useState(null);
    const [expandedItem, setExpandedItem] = useState(null);
    const [filters, setFilters] = useState({ search: "", status: "" });
    const [loading, setLoading] = useState(true);
    const [busy, setBusy] = useState("");
    const [message, setMessage] = useState("");
    const [error, setError] = useState("");

    const load = useCallback(async () => {
        setLoading(true);
        try {
            const { data } = await getQuotations(filters);
            setRecords(data);
            setError("");
        } catch (e) {
            setError(errorFor(e));
        } finally {
            setLoading(false);
        }
    }, [filters]);

    useEffect(() => {
        const timer = setTimeout(load, 250);
        return () => clearTimeout(timer);
    }, [load]);

    const run = async (id, action, successMsg) => {
        setBusy(id);
        setError("");
        try {
            await action();
            setSelected(null);
            setMessage(successMsg);
            await load();
        } catch (e) {
            setError(errorFor(e));
        } finally {
            setBusy("");
        }
    };

    const handleClientDecision = async (item, decision, selectedTier = null) => {
        let notes = "";
        if (decision === "Rejected") {
            const input = window.prompt("Optional: Provide a reason for declining all proposal price options:");
            if (input === null) return;
            notes = input;
        }
        setBusy(item._id);
        setError("");
        try {
            await clientDecideProposal(item._id, decision, notes || "", selectedTier);
            const tierLabel = selectedTier ? `${selectedTier.toUpperCase()} Tier` : "";
            setMessage(`Proposal ${item.quotationNumber} decision recorded (${decision} ${tierLabel}).`);
            await load();
        } catch (e) {
            setError(errorFor(e));
        } finally {
            setBusy("");
        }
    };

    return (
        <main className="quote-page">
            <header className="quote-page-header">
                <div>
                    <p className="quote-eyebrow">{isClientRole ? "Client Portal" : "Proposals & Estimates"}</p>
                    <h1>{isClientRole ? "Construction Proposals & Estimations" : "Building Proposals & Resource-Based Quotations"}</h1>
                    <p>{isClientRole ? "Submit building requests with your land details, view 3 Price Tier Options generated by Manager and verified by Admin, and Select or Reject options." : "Review client proposals against verified supplier capacity, generate 3-tier price offers, verify admin approvals, and dispatch to clients."}</p>
                </div>
                <div className="quote-total">
                    <strong>{records.length}</strong>
                    <span>proposals shown</span>
                </div>
            </header>

            {message && (
                <div className="quote-alert success">
                    {message}
                    <button onClick={() => setMessage("")}>×</button>
                </div>
            )}
            {error && <div className="quote-alert error">{error}</div>}

            <QuotationForm
                key={selected?._id || "new"}
                selected={selected}
                onCancel={() => setSelected(null)}
                onSaved={async (text) => {
                    setSelected(null);
                    setMessage(text);
                    await load();
                }}
            />

            <section className="quote-card">
                <div className="quote-heading">
                    <div>
                        <p className="quote-eyebrow">Register</p>
                        <h2>{isClientRole ? "My Building Proposals & Contractor Price Offers" : "Quotations & Resource Bids"}</h2>
                    </div>
                </div>

                <div className="quote-filters">
                    <label>
                        Search
                        <input
                            name="search"
                            placeholder="Number, title, location or tender reference"
                            value={filters.search}
                            onChange={(e) => setFilters((old) => ({ ...old, search: e.target.value }))}
                        />
                    </label>
                    <label>
                        Status
                        <select value={filters.status} onChange={(e) => setFilters((old) => ({ ...old, status: e.target.value }))}>
                            <option value="">All statuses</option>
                            {["Draft", "Submitted", "Approved", "Rejected", "Revised"].map((status) => (
                                <option key={status}>{status}</option>
                            ))}
                        </select>
                    </label>
                    <button className="quote-button ghost" onClick={() => setFilters({ search: "", status: "" })}>
                        Clear
                    </button>
                </div>

                <div className="quote-table-wrap">
                    <table className="quote-table">
                        <thead>
                            <tr>
                                <th>Proposal / Building Project</th>
                                <th>Land & Building Details</th>
                                <th>Site Location</th>
                                <th>Estimation / Offer</th>
                                <th>Admin Verification</th>
                                <th>Status</th>
                                <th>Actions & 3-Tier Price Options</th>
                            </tr>
                        </thead>
                        <tbody>
                            {records.map((item) => {
                                const isVerified = item.adminVerificationStatus === "Admin Verified";

                                return (
                                    <tr key={item._id}>
                                        <td>
                                            <strong>{item.quotationNumber}</strong>
                                            <span>{item.title}</span>
                                            {item.selectedTier && (
                                                <span style={{ fontSize: "11px", fontWeight: "800", color: "#059669", background: "#ecfdf5", padding: "2px 6px", borderRadius: "4px", display: "inline-block", marginTop: "4px" }}>
                                                    ⭐ Chosen: {item.selectedTier.toUpperCase()} Tier
                                                </span>
                                            )}
                                            {item.rejectionReason && (
                                                <small style={{ color: "#ef4444", display: "block", marginTop: "2px" }}>
                                                    Reason: {item.rejectionReason}
                                                </small>
                                            )}
                                        </td>
                                        <td>
                                            <div style={{ fontSize: "12px", color: "#334155", display: "grid", gap: "2px" }}>
                                                <div>🏢 <strong>{item.projectType || "Residential Building"}</strong></div>
                                                <div>📐 Area: <strong>{item.approximateAreaSqFt || 1500} Sq Ft</strong></div>
                                                <div>🪜 Floors: <strong>{item.numberOfFloors || 1} Floor(s)</strong></div>
                                            </div>
                                        </td>
                                        <td>
                                            <span style={{ fontSize: "12px", color: "#475569" }}>
                                                📍 {item.constructionSiteLocation || "Site Location Unspecified"}
                                            </span>
                                        </td>
                                        <td>
                                            {item.total > 0 ? (
                                                <strong>{item.total.toLocaleString()} {item.currency}</strong>
                                            ) : (
                                                <span style={{ fontSize: "12px", color: "#d97706", fontWeight: "700" }}>
                                                    Under Review & Estimation
                                                </span>
                                            )}
                                        </td>

                                        {/* Admin Verification Column */}
                                        <td>
                                            <span style={{
                                                padding: "4px 10px",
                                                borderRadius: "999px",
                                                fontSize: "11px",
                                                fontWeight: "800",
                                                background: isVerified ? "#dcfce7" : item.adminVerificationStatus === "Admin Rejected" ? "#fef2f2" : "#fffbeb",
                                                color: isVerified ? "#15803d" : item.adminVerificationStatus === "Admin Rejected" ? "#be123c" : "#b45309"
                                            }}>
                                                {item.adminVerificationStatus || "Pending Approval"}
                                            </span>
                                        </td>

                                        <td>
                                            <span className={`quote-status ${item.status.toLowerCase()}`}>
                                                {item.status === "Submitted" ? "Offer Ready for Review" : item.status}
                                            </span>
                                        </td>

                                        <td>
                                            <div className="quote-row-actions" style={{ flexDirection: "column", alignItems: "flex-start", gap: "6px" }}>
                                                {/* Toggle Line Items & Suppliers breakdown */}
                                                <button
                                                    className="quote-button ghost"
                                                    style={{ fontSize: "11px", padding: "4px 8px" }}
                                                    onClick={() => setExpandedItem(expandedItem === item._id ? null : item._id)}
                                                >
                                                    {expandedItem === item._id ? "▲ Hide Breakdown" : `▼ View Material Items (${item.items?.length || 0})`}
                                                </button>

                                                {/* Line Item Breakdown Drawer */}
                                                {expandedItem === item._id && (
                                                    <div style={{
                                                        background: "#f8fafc",
                                                        border: "1px solid #cbd5e1",
                                                        borderRadius: "8px",
                                                        padding: "10px",
                                                        fontSize: "12px",
                                                        width: "100%",
                                                        marginTop: "4px"
                                                    }}>
                                                        <strong style={{ display: "block", marginBottom: "6px", color: "#1e293b" }}>Priced Items & Material Specifications:</strong>
                                                        {item.items.map((line, idx) => (
                                                            <div key={idx} style={{ padding: "4px 0", borderBottom: idx < item.items.length - 1 ? "1px dashed #e2e8f0" : "none" }}>
                                                                <span>• {line.description} (Qty: {line.quantity} @ {line.unitPrice} {item.currency})</span>
                                                                {line.supplier && (
                                                                    <div style={{ color: "#2563eb", fontWeight: "600", fontSize: "11px" }}>
                                                                        🚢 Supplier Option: {line.supplier.supplierName} ({line.supplier.country || "Global"})
                                                                    </div>
                                                                )}
                                                            </div>
                                                        ))}
                                                    </div>
                                                )}

                                                {/* ADMIN ACTION: Verify Manager's 3-Tier Proposal Offer */}
                                                {isAdmin && item.adminVerificationStatus !== "Admin Verified" && item.tierOptions && (
                                                    <button
                                                        type="button"
                                                        className="quote-button primary"
                                                        style={{ background: "#059669", borderColor: "#059669", fontSize: "11px", marginTop: "4px" }}
                                                        disabled={busy === item._id}
                                                        onClick={() => run(item._id, () => adminVerifyProposal(item._id, "Admin Verified"), "Proposal offer verified by Admin and dispatched to Client!")}
                                                    >
                                                        🛡️ Admin Verify & Dispatch 3 Price Options Offer
                                                    </button>
                                                )}

                                                {/* CLIENT ACCEPTED STATUS & INVOICE PAYMENT LINK */}
                                                {item.clientDecision === "Accepted" && (
                                                    <div style={{ background: "#ecfdf5", border: "1px solid #a7f3d0", padding: "12px 16px", borderRadius: "10px", marginTop: "8px", display: "flex", justifyContent: "space-between", alignItems: "center", flexWrap: "wrap", gap: "10px", width: "100%" }}>
                                                        <div>
                                                            <div style={{ color: "#065f46", fontWeight: "800", fontSize: "13px" }}>
                                                                ✅ Proposal Accepted ({item.selectedTier ? item.selectedTier.toUpperCase() + ' Plan' : 'Standard Plan'})
                                                            </div>
                                                            <div style={{ color: "#047857", fontSize: "12px", marginTop: "2px" }}>
                                                                Official invoice generated & forwarded to Finance. Complete invoice payment to begin site construction.
                                                            </div>
                                                        </div>
                                                        <Link
                                                            to="/invoices"
                                                            style={{
                                                                padding: "7px 14px",
                                                                background: "#059669",
                                                                color: "#ffffff",
                                                                borderRadius: "8px",
                                                                textDecoration: "none",
                                                                fontWeight: "800",
                                                                fontSize: "12px",
                                                                display: "inline-flex",
                                                                alignItems: "center",
                                                                gap: "5px"
                                                            }}
                                                        >
                                                            💳 View Invoice & Pay →
                                                        </Link>
                                                    </div>
                                                )}

                                                {/* CLIENT DECISION PANEL: 3 PRICE OPTIONS OFFERED BY MANAGER */}
                                                {isVerified && item.tierOptions && item.status !== "Approved" && item.status !== "Rejected" && (
                                                    <div style={{
                                                        background: "#f0f9ff",
                                                        border: "1px solid #bae6fd",
                                                        borderRadius: "10px",
                                                        padding: "12px",
                                                        marginTop: "6px",
                                                        width: "100%"
                                                    }}>
                                                        <strong style={{ color: "#0369a1", fontSize: "12px", display: "block", marginBottom: "6px" }}>
                                                            🎁 Construction Price Options Offered:
                                                        </strong>

                                                        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: "8px", marginBottom: "8px" }}>
                                                            {/* Low Tier Option */}
                                                            {item.tierOptions.low && (
                                                                <div style={{ background: "#ffffff", border: "1px solid #cbd5e1", borderRadius: "8px", padding: "8px", textAlign: "center" }}>
                                                                    <div style={{ fontSize: "11px", color: "#64748b", fontWeight: "700" }}>OPTION 1: Low Budget</div>
                                                                    <div style={{ fontSize: "15px", fontWeight: "800", color: "#0f172a", margin: "2px 0" }}>
                                                                        BDT {item.tierOptions.low.totalCostBDT?.toLocaleString()}
                                                                    </div>
                                                                    <div style={{ fontSize: "10px", color: "#475569", marginBottom: "6px" }}>
                                                                        ~ BDT {item.tierOptions.low.estimatedCostPerSqFt} / Sq Ft
                                                                    </div>
                                                                    {isClientRole && (
                                                                        <button
                                                                            type="button"
                                                                            className="quote-button primary"
                                                                            style={{ background: "#475569", borderColor: "#475569", fontSize: "10px", padding: "4px 8px", width: "100%" }}
                                                                            disabled={busy === item._id}
                                                                            onClick={() => handleClientDecision(item, "Accepted", "low")}
                                                                        >
                                                                            Select Low Tier
                                                                        </button>
                                                                    )}
                                                                </div>
                                                            )}

                                                            {/* Standard Tier Option */}
                                                            {item.tierOptions.standard && (
                                                                <div style={{ background: "#eff6ff", border: "2px solid #2563eb", borderRadius: "8px", padding: "8px", textAlign: "center", position: "relative" }}>
                                                                    <span style={{ position: "absolute", top: "-8px", right: "6px", background: "#2563eb", color: "#fff", fontSize: "9px", fontWeight: "800", padding: "1px 5px", borderRadius: "4px" }}>RECOMMENDED</span>
                                                                    <div style={{ fontSize: "11px", color: "#1d4ed8", fontWeight: "700" }}>OPTION 2: Standard</div>
                                                                    <div style={{ fontSize: "15px", fontWeight: "800", color: "#1d4ed8", margin: "2px 0" }}>
                                                                        BDT {item.tierOptions.standard.totalCostBDT?.toLocaleString()}
                                                                    </div>
                                                                    <div style={{ fontSize: "10px", color: "#1e40af", marginBottom: "6px" }}>
                                                                        ~ BDT {item.tierOptions.standard.estimatedCostPerSqFt} / Sq Ft
                                                                    </div>
                                                                    {isClientRole && (
                                                                        <button
                                                                            type="button"
                                                                            className="quote-button primary"
                                                                            style={{ background: "#2563eb", borderColor: "#2563eb", fontSize: "10px", padding: "4px 8px", width: "100%" }}
                                                                            disabled={busy === item._id}
                                                                            onClick={() => handleClientDecision(item, "Accepted", "standard")}
                                                                        >
                                                                            Select Standard Tier
                                                                        </button>
                                                                    )}
                                                                </div>
                                                            )}

                                                            {/* Premium Tier Option */}
                                                            {item.tierOptions.premium && (
                                                                <div style={{ background: "#ffffff", border: "1px solid #c084fc", borderRadius: "8px", padding: "8px", textAlign: "center" }}>
                                                                    <div style={{ fontSize: "11px", color: "#7e22ce", fontWeight: "700" }}>OPTION 3: Premium</div>
                                                                    <div style={{ fontSize: "15px", fontWeight: "800", color: "#7e22ce", margin: "2px 0" }}>
                                                                        BDT {item.tierOptions.premium.totalCostBDT?.toLocaleString()}
                                                                    </div>
                                                                    <div style={{ fontSize: "10px", color: "#6b21a8", marginBottom: "6px" }}>
                                                                        ~ BDT {item.tierOptions.premium.estimatedCostPerSqFt} / Sq Ft
                                                                    </div>
                                                                    {isClientRole && (
                                                                        <button
                                                                            type="button"
                                                                            className="quote-button primary"
                                                                            style={{ background: "#7e22ce", borderColor: "#7e22ce", fontSize: "10px", padding: "4px 8px", width: "100%" }}
                                                                            disabled={busy === item._id}
                                                                            onClick={() => handleClientDecision(item, "Accepted", "premium")}
                                                                        >
                                                                            Select Premium Tier
                                                                        </button>
                                                                    )}
                                                                </div>
                                                            )}
                                                        </div>

                                                        {/* Client Decline All Options Button */}
                                                        {isClientRole && (
                                                            <div style={{ textAlign: "right" }}>
                                                                <button
                                                                    type="button"
                                                                    className="quote-button danger"
                                                                    style={{ fontSize: "10px", padding: "4px 8px" }}
                                                                    disabled={busy === item._id}
                                                                    onClick={() => handleClientDecision(item, "Rejected", null)}
                                                                >
                                                                    ❌ Reject All Options
                                                                </button>
                                                            </div>
                                                        )}
                                                    </div>
                                                )}

                                                {/* MANAGER ACTIONS: Edit & Submit Proposal */}
                                                {(isManager || isAdmin) && item.status === "Draft" && (
                                                    <div style={{ display: "flex", gap: "6px", marginTop: "4px" }}>
                                                        <button
                                                            className="quote-button edit"
                                                            onClick={() => { setSelected(item); window.scrollTo({ top: 0, behavior: "smooth" }); }}
                                                        >
                                                            Edit Bid
                                                        </button>
                                                        <button
                                                            className="quote-button ghost"
                                                            disabled={busy === item._id}
                                                            onClick={() => run(item._id, () => changeQuotationStatus(item._id, "Submitted"), "Proposal offer submitted for Admin verification.")}
                                                        >
                                                            Submit Offer
                                                        </button>
                                                    </div>
                                                )}
                                            </div>
                                        </td>
                                    </tr>
                                );
                            })}
                        </tbody>
                    </table>

                    {loading && <div className="quote-state">Loading proposals & estimations...</div>}
                    {!loading && !records.length && <div className="quote-state">No proposals found.</div>}
                </div>
            </section>
        </main>
    );
}

export default QuotationList;
